[build]
  command = "yarn build"
  publish = "build"

[forms.newsletter-signup.actions]
  [forms.newsletter-signup.actions.email]
    to = "info@terramedic.org"
    subject = "New Newsletter Signup"

[forms.contact-form.actions]
  [forms.contact-form.actions.email]
    to = "info@terramedic.org"
    subject = "New Contact Form Submission"